# -*- coding: utf-8 -*-
"""Notebook_Viviendas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_CVyfbFRA6xw_arj0r5DiMHqOSOSN6Bv
"""

!pip install https://github.com/pandas-profiling/pandas-profiling/archive/master.zip

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from ydata_profiling import ProfileReport

df = pd.read_csv("global_house_purchase.csv")

reporte = ProfileReport(df, title='Perfil de datos')

reporte.to_notebook_iframe()

df.info()

df.describe()

reporte.to_file(output_file="Perfil.html")